baseURL                   = "https://peterhanssens.com.au"
builddrafts                = false
languageCode               = "en"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

disqusShortname = "peterhanssens"

theme                      = "AllinOne"
title                      = "Peter Hanssens"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Projects"
    weight                 = -110
    identifier             = "projects"
    url                    = "projects/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

  [[menu.main]]
    name                   = "CV"
    weight                 = -90
    identifier             = "cv"
    url                    = "cv/"  

 

[params]
  faviconfile              = "img/peterhanssens.jpg"               # from static/
  avatar                   = "img/peterhanssens.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Peter Hanssens"
  description              = ["Architect.", "Engineer.", "Problem solver."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Keep being awesome!"
  welcome_word             = "~ There's nothing you can't do ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "phanssens1@gmail.com"
  github                   = "//github.com/phanssens1"
  linkedin                 = "//linkedin.com/in/peterhanssens"
  twitter                  = "//twitter.com/petehanssens" 
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "UA-78476101-1"
    
    
