[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "14.18.1"
 
[context.production]
  environment = { NODE_VERSION = "14", NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14", NODE_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_VERSION = "14", NODE_ENV = "production" }